### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by nemobis** [bufferapp/diggdigg#58]
Thanks for publishing the code, but what's the license? People cannot contribute legally if the software license is not stated.

**Comment by katzien** [comment]
Hey @sunils34 - do you have a hunch on what license we could apply here? I was thinking MIT based on http://choosealicense.com/ could work well... Also, are you able to see the settings option for this repo to use github's magical option to add a license? :smile:

**Comment by aronmarriott-smith** [comment]
As this is a WordPress plugin I think we should be using using GPL 2 or GPL 3:
https://wordpress.org/about/license/

**Comment by katzien** [comment]
Thanks @aronmarriott-smith, great one ! I just added the GNU GPL v3 to this repo :)

**Comment by nemobis** [comment]
Great! Thanks.
